### ISSUE TITLE
Add response on ping X-GitHub-Event

### ISSUE THREAD

**Issue by chinskiy** [pep8speaks-org/pep8speaks#32]
Greetings again
When I add webhook(according to https://github.com/OrkoHunter/pep8speaks/wiki/Instructions-to-deploy-a-fork#step-4--configure-webhooks) GitHub sent first request with `X-GitHub-Event: ping` in request header and app crashes
```
2017-04-26T19:47:44.333012+00:00 app[web.1]: [2017-04-26 19:47:44,332] ERROR in app: Exception on / [POST]
2017-04-26T19:47:44.333025+00:00 app[web.1]: Traceback (most recent call last):
2017-04-26T19:47:44.333028+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-04-26T19:47:44.333027+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2017-04-26T19:47:44.333029+00:00 app[web.1]:     return self.finalize_request(rv)
2017-04-26T19:47:44.333029+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1630, in finalize_request
2017-04-26T19:47:44.333028+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1615, in full_dispatch_request
2017-04-26T19:47:44.333030+00:00 app[web.1]:     response = self.make_response(rv)
2017-04-26T19:47:44.333033+00:00 app[web.1]:     raise ValueError('View function did not return a response')
2017-04-26T19:47:44.333030+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1725, in make_response
2017-04-26T19:47:44.333036+00:00 app[web.1]: ValueError: View function did not return a response

```
maybe it's more preferable to sent `Response(status=200)` ?
p.s. after this on pull request app works good.

**Comment by OrkoHunter** [comment]
@chinskiy The app doesn't technically "crash" and so this is just in the logs. But sure, it can be improved. Feel free to go ahead. :)

**Comment by chinskiy** [comment]
@OrkoHunter yes I understand that app still running and check PR but it confuses, I spent half of an hour thinking on whats wrong - why I got 500 in webhook response.
Okay, will make PR tomorrow.

**Comment by OrkoHunter** [comment]
Oh! I am really sorry for the confusion.

**Comment by chinskiy** [comment]
@OrkoHunter pull #34 merged - I this issue could be closed.
