### ISSUE TITLE
Heroku: ValueError: View function did not return a response

### ISSUE THREAD

**Issue by haeusser** [pep8speaks-org/pep8speaks#87]
Hi there,

first of all, thank you for the great tool. I am using pep8speaks following the instructions for a private repository since I am working on a student project.

Whenever a change to a PR is made, all I see in the Heroku logs is:

```
2018-04-30T10:54:36.117667+00:00 heroku[router]: at=info method=POST path="/" host=*****.herokuapp.com request_id=7b90fce9-c331-46d7-9f04-05988c8f7456 fwd="192.30.252.36" dyno=web.1 connect=1ms service=8ms status=500 bytes=456 protocol=https
2018-04-30T10:54:35.995560+00:00 app[web.1]: [2018-04-30 10:54:35,993] ERROR in app: Exception on / [POST]
2018-04-30T10:54:35.995600+00:00 app[web.1]: Traceback (most recent call last):
2018-04-30T10:54:35.995603+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
2018-04-30T10:54:35.995604+00:00 app[web.1]:     response = self.full_dispatch_request()
2018-04-30T10:54:35.995611+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1642, in full_dispatch_request
2018-04-30T10:54:35.995612+00:00 app[web.1]:     response = self.make_response(rv)
2018-04-30T10:54:35.995614+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1731, in make_response
2018-04-30T10:54:35.995615+00:00 app[web.1]:     raise ValueError('View function did not return a response')
2018-04-30T10:54:36.003656+00:00 app[web.1]: ValueError: View function did not return a response
2018-04-30T10:54:36.112292+00:00 app[web.1]: [2018-04-30 10:54:36,111] ERROR in app: Exception on / [POST]
2018-04-30T10:54:36.112296+00:00 app[web.1]: Traceback (most recent call last):
2018-04-30T10:54:36.112298+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
2018-04-30T10:54:36.112299+00:00 app[web.1]:     response = self.full_dispatch_request()
2018-04-30T10:54:36.112301+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1642, in full_dispatch_request
2018-04-30T10:54:36.112302+00:00 app[web.1]:     response = self.make_response(rv)
2018-04-30T10:54:36.112304+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1731, in make_response
2018-04-30T10:54:36.112305+00:00 app[web.1]:     raise ValueError('View function did not return a response')
2018-04-30T10:54:36.114493+00:00 app[web.1]: ValueError: View function did not return a response
2018-04-30T10:54:36.132060+00:00 app[web.1]: [2018-04-30 10:54:36,118] ERROR in app: Exception on / [POST]
2018-04-30T10:54:36.132064+00:00 app[web.1]: Traceback (most recent call last):
2018-04-30T10:54:36.132068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
2018-04-30T10:54:36.132069+00:00 app[web.1]:     response = self.full_dispatch_request()
2018-04-30T10:54:36.132071+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1642, in full_dispatch_request
2018-04-30T10:54:36.132072+00:00 app[web.1]:     response = self.make_response(rv)
2018-04-30T10:54:36.132073+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1731, in make_response
2018-04-30T10:54:36.132075+00:00 app[web.1]:     raise ValueError('View function did not return a response')
2018-04-30T10:54:36.140212+00:00 app[web.1]: ValueError: View function did not return a response
```

The response GitHub receives is an HTTP500 error:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Can anyone help me find the problem?

Thanks,
Philip

**Comment by haeusser** [comment]
When I open the heroku domain for my app, I arrive at the pep8speaks homepage. However, when I download the code from the heroku git repo, there is no code.

**Comment by OrkoHunter** [comment]
Hi @haeusser!

It has taken me long to get back to you. The `ValueError: View function did not return a response` is not a critical error in Heroku logs. It just means that for some types of payloads sent by Github, no action is taken i.e. No response is returned. As of now, most of the payloads receive a definite response, so you won't see a lot of these in the logs now (if you use the latest version).

I am going to close this issue. Please get back to me if you have any questions that I can answer. :)
